### ISSUE TITLE
Failed to create KMSEncryptionKey

### ISSUE THREAD

**Issue by lichadehehehe** [aws-samples/aws-iot-thingworx#4]
Failed to create KMSEncryptionKey (step 17), the error message is as follows:

`Resource handler returned message: "Policy contains a statement with one or more invalid principals. (Service: Kms, Status Code: 400, Request ID: a993b7f7-7150-4880-a82b-c2a1f296b1b2)" (RequestToken: 6b27fd83-d233-589a-e268-864c679b640e, HandlerErrorCode: InvalidRequest)`

![image](https://user-images.githubusercontent.com/83261960/213127343-2f0805ba-47bf-40f4-a316-4bb3ed7d5d9d.png)

Any assistance will be greatly appreciated.

**Comment by ntsaini** [comment]
Thanks for submitting the issue. I am able to recreate it and find the root cause. It is related to a circular dependency in cloudformation template. Will submit the pull request soon with the resolution.
